/**
 * tests/e2e/seo.spec.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Verifies that SEO-critical metadata, sitemap, and robots.txt
 * are correctly generated by Next.js at build time.
 *
 * Why test SEO in E2E?
 *   Unit tests can't verify that Next.js actually injects <meta> tags
 *   into the final HTML. Only a browser (or page.goto) can confirm this.
 */

import { test, expect } from '@playwright/test';

const DORM_IDS = ['namje', 'yongji', 'hwahong', 'gwanggyo', 'international', 'ilsin'];

test.describe('SEO: meta tags', () => {
  // ── Home ──────────────────────────────────────────────────────────────────────
  test('home has og:title and og:description', async ({ page }) => {
    await page.goto('/');
    const ogTitle = await page.locator('meta[property="og:title"]').getAttribute('content');
    const ogDesc  = await page.locator('meta[property="og:description"]').getAttribute('content');
    expect(ogTitle?.length).toBeGreaterThan(4);
    expect(ogDesc?.length).toBeGreaterThan(10);
  });

  test('home has canonical link', async ({ page }) => {
    await page.goto('/');
    const canonical = await page.locator('link[rel="canonical"]').getAttribute('href');
    expect(canonical).toBeTruthy();
  });

  test('home has twitter:card = summary_large_image', async ({ page }) => {
    await page.goto('/');
    const twitterCard = await page
      .locator('meta[name="twitter:card"]')
      .getAttribute('content');
    expect(twitterCard).toBe('summary_large_image');
  });

  // ── Per-dorm OG (KakaoTalk/에브리타임 공유 최적화) ─────────────────────────────────
  for (const dormId of DORM_IDS) {
    test(`/dorms/${dormId} has unique og:title and og:description`, async ({ page }) => {
      await page.goto(`/dorms/${dormId}`);

      const ogTitle = await page.locator('meta[property="og:title"]').getAttribute('content');
      const ogDesc  = await page.locator('meta[property="og:description"]').getAttribute('content');
      const ogImage = await page.locator('meta[property="og:image"]').getAttribute('content');

      // Title must mention the dorm (not just a generic title)
      expect(ogTitle?.length).toBeGreaterThan(4);
      // Description must be non-empty and within SNS limits
      expect(ogDesc?.length).toBeGreaterThan(10);
      expect((ogDesc?.length ?? 0)).toBeLessThanOrEqual(200);
      // Image URL must exist
      expect(ogImage).toBeTruthy();
    });
  }
});

test.describe('SEO: sitemap.xml and robots.txt', () => {
  test('sitemap.xml is accessible and contains home URL', async ({ page }) => {
    const response = await page.goto('/sitemap.xml');
    expect(response?.status()).toBe(200);
    const body = await response?.text();
    expect(body).toContain('<loc>');
    expect(body).toMatch(/<loc>https?:\/\/.*<\/loc>/);
  });

  test('sitemap.xml contains all 6 dorm detail URLs', async ({ page }) => {
    const response = await page.goto('/sitemap.xml');
    const body = (await response?.text()) ?? '';
    for (const dormId of DORM_IDS) {
      expect(body).toContain(`/dorms/${dormId}`);
    }
  });

  test('robots.txt is accessible and allows /', async ({ page }) => {
    const response = await page.goto('/robots.txt');
    expect(response?.status()).toBe(200);
    const body = (await response?.text()) ?? '';
    expect(body).toContain('Allow: /');
    expect(body).toContain('Disallow: /api/');
    expect(body).toContain('Sitemap:');
  });
});
